import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        
        <div
          className="absolute inset-0 -z-20"
          style={{
            backgroundImage: "url('/img/bg.png')",
            backgroundSize: 'cover',
            backgroundPosition: 'top',
            opacity: 1,
            pointerEvents: 'none',
          }}
        ></div>

        {children}

      </body>
    </html>
  );
}
