import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <div
          className="absolute inset-0 -z-10"
          style={{
        backgroundImage: "url('/img/light.png')",
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        opacity: 0.8,
        pointerEvents: 'none',
          }}
        />
        {children}
      </body>
    </html>
  );
}
